import type { RoomSnapshotView } from '../room-control/room-view-model';

export const roomFixtureSnapshot: RoomSnapshotView = {
    roomName: 'Local Smart Room',
    connectionStatus: 'fixture',
    updatedAt: '2026-06-05T10:20:12Z',
    devices: [
        {
            deviceId: 'led-main',
            name: 'Main LED',
            role: 'led-output',
            health: 'online',
            reportedState: { power: 'off' },
            requestedState: { power: 'on' },
            commandAvailability: {
                policy: 'allow',
            },
            lastSeenAt: '2026-06-05T10:20:11Z',
            activeCommandId: 'cmd-led-on-001',
        },
        {
            deviceId: 'temp-desk',
            name: 'Desk Temperature',
            role: 'temperature-sensor',
            health: 'online',
            reportedState: { temperature: 22.4, unit: 'celsius' },
            commandAvailability: {
                policy: 'block',
                reason: 'Sensor-only device does not accept commands.',
            },
            lastSeenAt: '2026-06-05T10:20:10Z',
        },
        {
            deviceId: 'humidity-window',
            name: 'Window Humidity',
            role: 'humidity-sensor',
            health: 'stale',
            reportedState: { humidity: 48, unit: 'percent' },
            commandAvailability: {
                policy: 'allow_with_warning',
                reason: 'Device state is stale; commands require visible uncertainty.',
            },
            lastSeenAt: '2026-06-05T10:14:22Z',
            warning: 'Last reading is outside the freshness window.',
        },
        {
            deviceId: 'motion-door',
            name: 'Door Motion',
            role: 'motion-sensor',
            health: 'offline',
            reportedState: { motion: false },
            commandAvailability: {
                policy: 'block',
                reason: 'Device crossed the offline threshold.',
            },
            lastSeenAt: '2026-06-05T09:58:03Z',
            warning: 'Device crossed the offline threshold.',
        },
        {
            deviceId: 'ambient-shelf',
            name: 'Shelf Ambient Light',
            role: 'ambient-light-sensor',
            health: 'degraded',
            reportedState: { illuminance: 126, unit: 'lux' },
            commandAvailability: {
                policy: 'allow_with_warning',
                reason: 'Partial readings are available; commands may be limited.',
            },
            lastSeenAt: '2026-06-05T10:19:40Z',
            warning: 'Partial readings are available; commands may be limited.',
        },
    ],
    activeCommands: [
        {
            commandId: 'cmd-led-on-001',
            deviceId: 'led-main',
            commandType: 'set.power',
            status: 'pending',
            requestedState: { power: 'on' },
            requestedAt: '2026-06-05T10:20:08Z',
            dispatchedAt: '2026-06-05T10:20:09Z',
            message: 'Waiting for adapter-produced device.state.reported.',
        },
    ],
    recentEvents: [
        {
            eventId: 'evt-1003',
            eventType: 'command.dispatched',
            occurredAt: '2026-06-05T10:20:09Z',
            source: 'backend',
            deviceId: 'led-main',
            commandId: 'cmd-led-on-001',
            summary: 'Backend dispatched set.power to simulator-adapter.',
        },
        {
            eventId: 'evt-1002',
            eventType: 'command.requested',
            occurredAt: '2026-06-05T10:20:08Z',
            source: 'backend',
            deviceId: 'led-main',
            commandId: 'cmd-led-on-001',
            summary: 'User requested Main LED power on.',
        },
        {
            eventId: 'evt-1001',
            eventType: 'device.state.reported',
            occurredAt: '2026-06-05T10:20:05Z',
            source: 'simulator-adapter',
            deviceId: 'temp-desk',
            summary: 'Desk Temperature reported 22.4 celsius.',
        },
        {
            eventId: 'evt-1000',
            eventType: 'device.health.changed',
            occurredAt: '2026-06-05T10:16:22Z',
            source: 'backend',
            deviceId: 'humidity-window',
            summary: 'Window Humidity became stale after missing fresh telemetry.',
        },
    ],
};
